# Generated by Django 3.2 on 2021-06-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('institute', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('started_at', models.CharField(blank=True, max_length=30)),
                ('ended_at', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('describe', models.CharField(blank=True, max_length=100)),
                ('started_at', models.CharField(blank=True, max_length=30)),
                ('ended_at', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('details', models.CharField(blank=True, max_length=400)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='me')),
                ('about_image', models.ImageField(blank=True, upload_to='me')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('experience', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
