# Generated by Django 3.2 on 2021-06-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('details', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='project')),
                ('view_online', models.CharField(blank=True, max_length=50)),
                ('technology_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
